VB-77 Fileuploader, show error message
vektorprogrammet/vektor-backend pull request #162
Opened 2022-10-05 17:58 UTC by assi98

Small change. Alert the user when they try to upload a to big receipe file.

2022-10-08 13:16 UTC, Lundli requested changes
This change seems to break the styling/css of the utlegg-page.
The styling disappears when the page is reloaded.

![image](https://user-images.githubusercontent.com/46197518/194709495-03d03876-3c27-41b0-aacd-231e99ad9cd1.png)


See commit f948c82e4f911f8a55f1f2ca50a4ea0e3982a0ac which fixes the form layout.

2022-10-08 19:09 UTC, Lundli commented
When notifying the user about the error (image too large), I would suggest you use `addFlash` to be consistent with other pages.
`$this->addFlash('warning', "text here");`

It would then look like this:
![image](https://user-images.githubusercontent.com/46197518/194723583-68c5ae3e-148d-482b-951c-76ab032a28dd.png)

Example can be found here:
https://github.com/vektorprogrammet/vektor-backend/blob/18a24c51ebcf444e1403d3e533ecc885ea72f374/src/Controller/SemesterController.php#L56

2022-10-11 16:12 UTC, assi98 commented
Are now using flash note and it seem to have fixed css issues: 
![image](https://user-images.githubusercontent.com/55314729/195144506-794eb38c-a369-48fb-beb2-675f1744cc45.png)

2022-10-11 18:01 UTC, Lundli commented on src/Controller/ReceiptController.php
> +            $this->addFlash('warning', "The file is too large. Allowed maximum size is 2 MiB.)");
Rememeber that this page is in norwegian. Error messages shown to user should be as well.

2022-10-12 15:31 UTC, Lundli commented on src/Controller/ReceiptController.php
> +        if ($form->isSubmitted() && !$form->isValid()&& $receipt->getPicturePath()=="") {
```suggestion
        if ($form->isSubmitted() && !$form->isValid()&& $receipt->getPicturePath() == "") {
```

2022-10-12 15:47 UTC, Lundli commented on package-lock.json
> +    "@ampproject/remapping": {
Looks great! :100: 

For information:
We have moved from `npm` to `yarn`.
You should get new changes from upstream, and re-create lock files using yarn (`yarn.lock`).

**TODOs:**
- [ ] Merge incoming upstream changes
- [ ] Fix suggested changes
Should be good after that!

2022-10-18 14:55 UTC, Lundli approved these changes
:100:

2022-10-18 15:09 UTC, merged